---
name: Geo-Address-Mail-Standardizer-USPS-AMS
version: 0.02
abstract: address standardization using the United States Postal Service Address Matching System
author:
    - Mike Eldridge <diz@cpan.org>
license: perl
distribution_type: module
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    ExtUtils::MakeMaker: 0
requires:
  Geo::Address::Mail::US: 0.01
  Geo::Address::Mail::Standardizer: 0.02
  Geo::Address::Mail::Standardizer::USPS::AMS::Results: 0.02
  Moose: 0.90
no_index:
    directory:
        - t
        - inc
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
